### ISSUE TITLE
openslides_bin for repo use

### ISSUE THREAD

**Issue by FinnStutzenstein** [ostcar/openslides_ansible#3]
I try to add support for Raspbian jessy. But one general question: If One use the github repository, which file is going to be the `openslides_bin`? I mean in development I use the `python manage.py` for handling OpenSlides. 

Ansible:
```
TASK [openslides_ansible : Migrate Database] ***********************************
fatal: [10.42.7.229]: FAILED! => {"changed": false, "cmd": "/usr/local/bin/openslides migrate --pythonpath /etc/openslides --settings settings --noinput", "failed": true, "msg": "[Errno 2] Datei oder Verzeichnis nicht gefunden", "rc": 2}
```

**Comment by ostcar** [comment]
Of cause, you could use python manage.py. But I think it is easier to install openslides so there is the same openslides_bin for an install from git or from pypi.

If you install OpenSlides from git, then it is installed with the task "Install openslides from repo" which is currently on line 112:
```yml
- name: Install openslides from repo
  when: openslides_use_git and OpenSlidesGit.changed
  become: yes
  pip:
    name: file:///var/cache/openslides_repo
    executable: "{{ pip_executable }}"
    state: latest
```
This is the same, as if you would call ``` pip install .``` inside the github repo or ```python setup.py install```. This installs the script ```openslides``` at a distribution specific place. I think it is ```/usr/local/bin/``` but I am not sure. 

Could you run ```pip install .``` inside the openslides repo on you installation and then search for the openslides script? I think the command ```type openslides``` should help you with that.
